### ISSUE TITLE
STOP/Opt-out ability with this application?

### ISSUE THREAD

**Issue by HSteeleLTS** [jweisman/Alma-AWS-Lambda#13]
Hey this looks like a great way to integrate Alma with Twilio for patron text notifications.  I do have a question.  We are investigating whether we are going to implement this or not, and our IT department has a concern about whether patrons can opt out if they receive an SMS message from Alma.  Is there functionality for this in this integration, or included on the Twilio end?

**Comment by jweisman** [comment]
Hi @HSteeleLTS . This functionality is part of Alma itself. See below, for example, the ability to set an SMS flag on a phone number.

<img width="658" alt="Screen Shot 2022-04-11 at 10 54 10 " src="https://user-images.githubusercontent.com/80420/162690727-2437b99e-5d41-495f-ab32-e24f49f57736.png">

More information is available in the [online help](https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/090Integrations_with_External_Systems/040Fulfillment/070SMS_Communications).

**Comment by HSteeleLTS** [comment]
That’s great to hear !    Does that mean if a patron sends a stop request the number is removed from their Alma record ?   Of course one way we’d get these numbers is in a feed , so the logistics of that solution we’d have to think about more , like if a patron issues a stop request can we prevent the number from coming in the feed.   But another possible solution is the patron gives us their number so if the number was erased by a stop requests in that scenario then we wouldn’t have to worry about it coming back in

**Comment by jweisman** [comment]
From what I understand from the online help, the patron can update their SMS phone number from Primo or by staff in Alma. If there is no SMS phone number, the notification will not be sent via the SMS channel. Hope that helps.

**Comment by HSteeleLTS** [comment]
THat's really interesting to know.  I wasn't aware of this.  Could you send me the relevant OLH page?  This capability of the patron being able to set and change their cell number for SMS is really the ideal state we'd like.  So I'd be very interested to pursue this capabiltiy

**Comment by jweisman** [comment]
Sure- see the link above:
https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/090Integrations_with_External_Systems/040Fulfillment/070SMS_Communications

You can also open a support ticket to get more details.

**Comment by HSteeleLTS** [comment]
Hmm.  I’m not sure what I’m supposed to be seeing here.   

Also for Primo VE it seems like this is not an option: 
https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/090Integrations_with_External_Systems/040Fulfillment/070SMS_Communications

**Comment by HSteeleLTS** [comment]
Do you have any more context on this ?  Is it true this is not an option for Primo VE or is there some workaround that would make this possible?

**Comment by HSteeleLTS** [comment]
Sorry.  You mentioned that I should check with support on this.  I just submitted a ticket [06356557](https://support.proquest.com//s/case/5003r00001TokU9AAJ)
